### PR TITLE
Bandit stability fixes

### PR DESCRIPTION
**Pull request by aasseman**
Refer to commit messages.

### CODE REVIEW

**Comment by aasseman** [comment]
I'll add a test to substantiate my claims...

**Comment by aasseman** [comment]
The commit above ([e7c7302](https://github.com/semiotic-ai/autoagora-agents/pull/32/commits/e7c7302fc80f905178c9abe09d70e456435e87b6)) adds the test showing the problem.

**Review by tkornuta-semiotic — DISMISSED** [review]
Please update the comments. Aside of that - LGTM! :)

**Comment by aasseman** [comment]
Fixed the `ScaledGaussianAction` docstring.

**Review by tkornuta-semiotic — APPROVED** [review]

**Pull request merged**
