### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by anirudh2**
Just creating some documentation on how to configure and run v2.

### CODE REVIEW

**Review by aasseman — DISMISSED** [review]
LGTM!

**Comment by anirudh2** [comment]
Completely forgot about this lol. Thanks, @aasseman! 

@tkornuta-semiotic @tumaysem, just a reminder in case y'all also forgot.

**Comment by aasseman** [comment]
@anirudh2 forgot about this one. Could you rebase + merge this one?

**Comment by anirudh2** [comment]
@aasseman I don't have permission to push to the doc-update branch for some reason anymore.

**Pull request merged**
